EVALUATE
UNION (
    ROW (
        "Table", "Produto Categoria",
        "Column", "ID Categoria",
        "Count", COUNT ( 'Produto Categoria'[ID Categoria] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'Produto Categoria'[ID Categoria] ),
        "Null Count", COUNTROWS ( 'Produto Categoria' ) - COUNT ( 'Produto Categoria'[ID Categoria] ),
        "Min", MIN ( 'Produto Categoria'[ID Categoria] ),
        "Max", MAX ( 'Produto Categoria'[ID Categoria] ),
        "Median", MEDIAN ( 'Produto Categoria'[ID Categoria] ),
        "Mean", AVERAGE ( 'Produto Categoria'[ID Categoria] ),
        "Standard Deviation", STDEV.P ( 'Produto Categoria'[ID Categoria] ),
        "Zeros", COALESCE ( COUNTROWS ( FILTER ( 'Produto Categoria', 'Produto Categoria'[ID Categoria] = 0 ) ), 0 ),
        "Evens", COALESCE ( COUNTROWS ( FILTER ( 'Produto Categoria', MOD ( 'Produto Categoria'[ID Categoria], 2 ) = 0 ) ), 0 ),
        "Odds", COALESCE ( COUNTROWS ( FILTER ( 'Produto Categoria', MOD ( 'Produto Categoria'[ID Categoria], 2 ) <> 0 ) ), 0 ),
        "P25", PERCENTILE.INC ( 'Produto Categoria'[ID Categoria], 0.25 ),
        "P75", PERCENTILE.INC ( 'Produto Categoria'[ID Categoria], 0.75 ),
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    ),
    ROW (
        "Table", "Produto Categoria",
        "Column", "Categoria",
        "Count", COUNT ( 'Produto Categoria'[Categoria] ),
        "Distinct Values", DISTINCTCOUNTNOBLANK ( 'Produto Categoria'[Categoria] ),
        "Null Count", COUNTROWS ( 'Produto Categoria' ) - COUNT ( 'Produto Categoria'[Categoria] ),
        "Min", MIN ( 'Produto Categoria'[Categoria] ),
        "Max", MAX ( 'Produto Categoria'[Categoria] ),
        "Median", "N/A",
        "Mean", "N/A",
        "Standard Deviation", "N/A",
        "Zeros", "N/A",
        "Evens", "N/A",
        "Odds", "N/A",
        "P25", "N/A",
        "P75", "N/A",
        "Range in Days", "N/A",
        "Range in Months", "N/A",
        "Range in Years", "N/A"
    )
)