table Lojas
	lineageTag: 529c2aae-c665-4b71-ab81-85dee72658b3

	column 'ID Loja'
		dataType: double
		isHidden
		lineageTag: e3385803-d05c-465f-a7f4-870c0bd152a5
		summarizeBy: none
		sourceColumn: ID Loja

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'ID Localização '
		dataType: double
		isHidden
		lineageTag: 51a6737e-7cf7-4685-9684-052f93b3e5bd
		summarizeBy: none
		sourceColumn: "ID Localização "

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Tipo
		dataType: string
		lineageTag: 73476101-1eaf-47ca-88b5-43dea2b284bb
		summarizeBy: none
		sourceColumn: Tipo

		annotation SummarizationSetBy = Automatic

	column Nome
		dataType: string
		lineageTag: dddf4f9a-522b-4ab3-a37f-a75bea7c46b1
		summarizeBy: none
		sourceColumn: Nome

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: baf99473-9bd0-4c78-a52c-61d8da0079b9
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Total Funcionários'
		dataType: double
		lineageTag: 21c227b2-9a82-4d83-96f1-e10fe09b1bd7
		summarizeBy: sum
		sourceColumn: Total Funcionários

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Tamanho
		dataType: double
		lineageTag: 6ef69d4f-feb0-4476-8b33-b3ca3ebe766d
		summarizeBy: sum
		sourceColumn: Tamanho

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Lojas-9adb2fe5-82cc-4247-9cbf-199daa1f6820 = m
		mode: import
		source =
				let
				    Source = Access.Database(File.Contents("C:\Users\owend\Documents\ContosoSalesV31_64bit.accdb")),
				    _DimStores = Source{[Schema="",Item="DimStores"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(_DimStores,{"StoreManager", "CloseDate", "OpenDate", "ZipCode", "ZipCodeExtension", "StorePhone", "StoreFax", "AddressLine1", "AddressLine2", "LastRemodelDate", "GeoLocation", "Geometry", "ETLLoadID", "LoadDate", "UpdateDate", "EntityKey", "StoreDescription"}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Removed Columns",{{"StoreKey", "ID Loja"}, {"GeographyKey", "ID Localização "}, {"StoreType", "Tipo"}, {"StoreName", "Nome"}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Colunas Renomeadas",{"CloseReason"}),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Colunas Removidas",{{"EmployeeCount", "Total Funcionários"}, {"SellingAreaSize", "Tamanho"}})
				in
				    #"Colunas Renomeadas1"

	changedProperty = Name

	annotation ColumnsMetadata = {"Columns":[{"Name":"StoreKey","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimStores.{StoreKey,0}"},{"Name":"GeographyKey","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimStores.{GeographyKey,1}"},{"Name":"StoreType","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimStores.{StoreType,3}"},{"Name":"StoreName","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimStores.{StoreName,4}"},{"Name":"Status","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimStores.{Status,6}"},{"Name":"CloseReason","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimStores.{CloseReason,16}"},{"Name":"EmployeeCount","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimStores.{EmployeeCount,17}"},{"Name":"SellingAreaSize","Id":"Server.Database\\/1/File/c:\\\\users\\\\owend\\\\documents\\\\contososalesv31_64bit.accdb//DimStores.{SellingAreaSize,18}"}]}

	annotation PBI_ResultType = Exception

